# values.yaml for kube-prometheus-stack
grafana:
  admin:
    existingSecret: grafana-admin-secret
    secretKey: admin-password

  ## Persistence configuration
  ##
  persistence:
    enabled: true
    ## grafana data Persistent Volume access modes
    ## Must match your volume's access modes
    ##
    accessModes:
      - ReadWriteOnce
    ## grafana data Persistent Volume size
    ##
    size: 10Gi
    ## grafana data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClassName: "longhorn" # 请根据你的环境修改或取消注释
